services:
  backend:
    build:
      context: ./BE
    restart: always
    env_file:
      - ./BE/.env
    volumes:
      - backend_images:/app/images
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./FE
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes: backend_images
