type User {
  _id: ID!
  name: String!
  status: String!
  createdAt: String!
  updatedAt: String!
}

type Post {
  _id: ID!
  content: String!
  imageUrl: String
  creator: User!
  createdAt: String!
  updatedAt: String!
}

type AuthData {
  token: String!
  userId: String!
  expiresIn: Int!
}

type StatusData {
  status: String!
}

type PostsData {
  posts: [Post!]!
  totalItems: Int!
  pageInfo: PageInfo!
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
}

input UserInputData {
  email: String!
  name: String!
  password: String!
}

input PostInputData {
  content: String!
  imageUploadId: ID
  removeImage: Boolean = false
}

type RootQuery {
  posts(first: Int, after: String, creatorId: ID): PostsData!
  post(id: ID!): Post!
  user(id: ID!): User!
  status: StatusData!
}

type RootMutation {
  createUser(userInput: UserInputData!): User!
  login(email: String!, password: String!): AuthData!
  createPost(postInput: PostInputData!): Post!
  updatePost(id: ID!, postInput: PostInputData!): Post!
  deletePost(id: ID!): Boolean!
  updateStatus(status: String!): StatusData!
}

schema {
  query: RootQuery
  mutation: RootMutation
}
