mutation CreateUser($email: String!, $name: String!, $password: String!) {
  createUser(userInput: { email: $email, name: $name, password: $password }) {
    _id
  }
}

mutation Login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    token
    userId
    expiresIn
  }
}

query GetStatus {
  status {
    status
  }
}

mutation UpdateStatus($status: String!) {
  updateStatus(status: $status) {
    status
  }
}

fragment PostFields on Post {
  _id
  content
  imageUrl
  createdAt
  updatedAt
  creator {
    _id
    name
  }
}

query GetPosts($first: Int, $after: String, $creatorId: ID) {
  posts(first: $first, after: $after, creatorId: $creatorId) {
    totalItems
    pageInfo {
      endCursor
      hasNextPage
    }
    posts {
      ...PostFields
    }
  }
}

query GetPost($id: ID!) {
  post(id: $id) {
    ...PostFields
  }
}

query GetUser($id: ID!) {
  user(id: $id) {
    _id
    name
    status
  }
}

mutation CreatePost($postInput: PostInputData!) {
  createPost(postInput: $postInput) {
    ...PostFields
  }
}

mutation UpdatePost($id: ID!, $postInput: PostInputData!) {
  updatePost(id: $id, postInput: $postInput) {
    ...PostFields
  }
}

mutation DeletePost($id: ID!) {
  deletePost(id: $id)
}
